spring.application.name=buffet

server.port=${PORT:8080}

product.db.host=${PRODUCT_DB_HOST:localhost}
product.db.port=${PRODUCT_DB_PORT:3306}
product.db.name=${PRODUCT_DB_NAME:product}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tda_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:strongPassword?}

spring.datasource.url=jdbc:mysql://${product.db.host}:${product.db.port}/${product.db.name}?useSSL=true&characterEncoding=UTF-8
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=always

spring.web.error.include-message=always
